### ISSUE TITLE
About inter.c

### ISSUE THREAD

**Issue by hidaehyunlee** [LesChats/Exam02_simple_func#1]
Hi.
I took the exam yesterday for exam02 inter, referring to your code, and I got a fail.
I'm not blaming you at all!! 😅 
I just want to know the difference between your code and mine. 
Can you check what the problem is with my code?
Thank you.

```c
#include <unistd.h>

int     main(int ac, char **av)
{
    int ascii[256];
    char *s1 = av[1];
    char *s2 = av[2];
    int  i = 0;
    
    if (ac != 3)
    {
        write(1, "\n", 1);
        return (0);
    }
    while (i < 256)
        ascii[i++] = 0;
    i = 0;
    while (s2[i])
    {
        ascii[s2[i]] = 1;
        i++;
    }
    i = 0;
    while (s1[i])
    {
        if (ascii[s1[i]] == 1)
        {   
            write(1, &s1[i], 1);
            ascii[s1[i]] = 2;
        }
        i++;
    }
    write(1, "\n", 1);
    return (0);
}
```

<br>

And this is my union.c
```c
int     main(int ac, char **av)
{
    int i = 0;
    char *s1 = av[1];
    char *s2 = av[2];
    int ascii[256];

    if (ac != 3)
    {
        write(1, "\n", 1);
        return (0);
    }
    while (i < 256)
        ascii[i++] = 0;
    i = 0;
    while (s1[i])
    {
        write(1, &s1[i], 1);
        ascii[s1[i]] = 1;
        i++;
    }
    i = 0;
    while (s2[i])
    {
        if (ascii[s2[i]] == 0)
        {
            write(1, &s2[i], 1);
            ascii[s2[i]] = 1;
        }
        i++;
    }
    write(1, "\n", 1);
    return (0);
}
```

**Comment by LesChats** [comment]
Hello, 
First I'm really sorry you fail the exam02, but I'm also glad you reach me ;)
This is where your  **inter.c** may fail :
` char *s1 = av[1];`
` char *s2 = av[2];`
the reasons could be :  

1. As you did not check if these addresses were available. Then your program must have got some kind of **bus error/ segfault** wit that kind of entry :
`./inter "hello"`
`./inter`
You may haven't noticed this behavior on your system, but the exam environment can be a lot more restrictive on the memory access.

2. The cast in "char" who range trough -[126, 125]  could go wrong with a test like this one : 
`./inter "tést" "tést"`

The rest of your inter seem correct, so following your style this should be good : 

```C
#include <unistd.h>

int main(int ac, char **av)
{
	int ascii[256];
	unsigned char *s1, *s2;
	int i = 0;

	if (ac == 3)
	{
		s1 = av[1]; s2 = av[2];
		while (i < 256)
			ascii[i++] = 0;
		i = 0;
		while (s2[i])
			ascii[s2[i++]] = 1;
		i = 0;
		while (s1[i])
		{
			if (ascii[s1[i]] == 1)
			{
				write(1, s1 + i, 1);
				ascii[s1[i]] = 2;
			}
			++i;
		}
	}
	write(1, "\n", 1);
	return (0);
}

```
Best regard and luck for next week <3

**_PS : careful your **union.c** is wrong !!! Reach me on discord if you need anything_** `Alors#6099`

**Comment by hidaehyunlee** [comment]
Thank you **SO MUCH** for your kind reply!!
I understand the cast in "char" could be a problem. 😭 

By the way, in your reason1, I think this is a more fundamental question about programming, how should I check some addresses were available or not? I don't know how to find a test cases that bus error or segfault occur, including your example case.. Is it just too obvious for you? Or can I debug myself in a simple way on exam? 😭 

**+**
Your code is really simple and great. By the way, in your **inter.c**, is changing to `int` datatype a must? like `hash_t[(int)*av[2]++] = 1;`.. I just wanted to know why you didn't do that in **union.c** code. 

You can close this issue if you are busy. :) Thank you so much for the answer. Have a good day!

**Comment by LesChats** [comment]
Must say I'm a learner just as you and our 42 pairs. 
The reason **1.** was my first guess, but after disputing the issue with a friend I learn that in POSIX system the address following av[0] automatically point to the environment as we can test running this small program : 
```C
#include <stdio.h>
int main(int ac, char **av) {
      printf("%s", av[2]);
}
```
So, considering that MacOs comms out from POSIX reason n1 is quite unlikely the good one :joy:
(also I test it at home on Linux (so is POSIX) with -fsanitize=address and that didn't raise any warning so let say that this is definitely not the reason that you fail the test).

However, I didn't edit that part of my answer because I believe that this is a bad (I don't know how to say ...) "style" that can lead to bad behavior. In exam session just check with -fsanitize=address, but it should be good.

So reason 2. Is the strongest candidate, and we couldn't find another one.

**+**
No the explicit casting that I did in **inter.c** is not a must :joy:
That is how the compiler will translate it but it doesn't have to be explicit, as I show it in **union.c**.

Thank you again for your question, I learn things will trying to answers it, so we both win :)))))) <3

**Comment by hidaehyunlee** [comment]
Thank you for telling me that my question helped you. :) It was my first time communicating with another 42 campus cadet, and I learned a lot.. thanks to your kindness. As you said, 42 are the one! 😃😃😃  

If you don't mind, I'll close this issue! Thanks a lot!!!! :))
